name: Daily Financial Analysis # Workflow 的名称

on:
  workflow_dispatch: # 允许手动触发
  schedule:
    # 在每天的特定时间运行 (UTC 时间)
    # 例如：每天 23:00 UTC 运行 (对应北京时间早上 7:00)
    # 使用 crontab 格式: 分 时 日 月 周
    # 更多信息: https://pubs.opengroup.org/onlinepubs/9699919799/utilities/crontab.html#tag_20_25_07
    - cron: '0 17 * * *'

jobs:
  run-analysis:
    runs-on: ubuntu-latest # 使用最新的 Ubuntu 运行环境
    steps:
      - name: Checkout repository # 第一步：检出你的代码
        uses: actions/checkout@v4 # 使用官方的 checkout action

      - name: Set up Python # 第二步：设置 Python 环境
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # 指定你希望使用的 Python 版本

      - name: Install dependencies # 第三步：安装依赖
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; else echo "requirements.txt not found."; exit 1; fi

      - name: Run Python script # 第四步：运行你的脚本
        env: # 设置环境变量，从 GitHub Secrets 读取值
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          TO_EMAIL: ${{ secrets.TO_EMAIL }}
        run: python financial_analysis.py # 运行你的 Python 文件 (确保文件名匹配)